from __future__ import annotations

from enum import Enum
from typing import Callable, Iterable, Optional, Sequence


class DType(Enum):
    F32: int
    F16: int
    I32: int
    U8: int
    Q8_0: int
    Q4_0: int


class DeviceInfo:
    platform_name: str
    platform_vendor: str
    device_name: str
    device_vendor: str
    driver_version: str
    device_version: str
    extensions: str
    global_mem_size: int
    local_mem_size: int
    compute_units: int
    max_work_group_size: int


class ProfileRecord:
    name: str
    ms: float


class ProfileSummary:
    name: str
    count: int
    total_ms: float
    avg_ms: float
    max_ms: float


class Backend:
    @staticmethod
    def opencl(kernel_dir: str = "") -> Backend: ...
    @staticmethod
    def create() -> Backend: ...
    def finish(self) -> None: ...
    def device_info(self) -> DeviceInfo: ...
    def supports_integer_dot(self) -> bool: ...
    def int_dot_mode(self) -> str: ...
    def supports_command_buffer(self) -> bool: ...
    def supports_command_buffer_mutable_dispatch(self) -> bool: ...
    def command_buffer_mode(self) -> str: ...
    def profile_set_enabled(self, enabled: bool) -> None: ...
    def profile_enabled(self) -> bool: ...
    def profile_clear(self) -> None: ...
    def profile_records(self) -> list[ProfileRecord]: ...
    def profile_summary(self) -> list[ProfileSummary]: ...


class Tensor:
    @property
    def shape(self) -> list[int]: ...
    @property
    def dtype(self) -> DType: ...
    @property
    def requires_grad(self) -> bool: ...
    def id(self) -> int: ...
    def cpu(self) -> list[float]: ...
    def cpu_i32(self) -> list[int]: ...
    def item(self) -> float: ...
    def backward(self) -> None: ...
    def set_requires_grad(self, value: bool = True) -> None: ...
    def view(self, shape: Sequence[int]) -> Tensor: ...
    def __add__(self, other: Tensor) -> Tensor: ...
    def __radd__(self, other: Tensor) -> Tensor: ...
    def __sub__(self, other: Tensor) -> Tensor: ...
    def __rsub__(self, other: Tensor) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __rmul__(self, other: Tensor | float | int) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def __neg__(self) -> Tensor: ...


class QKV:
    q: Tensor
    k: Tensor
    v: Tensor


class SafeTensorInfo:
    name: str
    dtype: str
    shape: list[int]
    data_begin: int
    data_end: int


class SafeTensorsFile:
    @staticmethod
    def open(path: str) -> SafeTensorsFile: ...
    def path(self) -> str: ...
    def tensor_names(self) -> list[str]: ...
    def contains(self, name: str) -> bool: ...
    def tensor_info(self, name: str) -> SafeTensorInfo: ...
    def load_tensor(self, backend: Backend, name: str, force_f32: bool = True) -> Tensor: ...
    def load_f32_vector(self, name: str) -> list[float]: ...


class TensorSpec:
    id: int
    dtype: DType
    nbytes: int
    dynamic_shape: bool
    @property
    def shape(self) -> list[int]: ...


class GraphBufferAllocation:
    allocation_id: int
    tensor_ids: list[int]
    bytes: int
    first_node: int
    last_node: int


class GraphBufferPlan:
    allocations: list[GraphBufferAllocation]
    peak_bytes: int
    total_output_bytes: int
    reused_bytes: int
    shape_polymorphic: bool


class GraphRuntimeBinding:
    tensor_id: int
    allocation_id: int
    offset: int
    nbytes: int
    dtype: DType
    @property
    def shape(self) -> list[int]: ...


class GraphRuntimePlan:
    buffer_plan: GraphBufferPlan
    runtime_specs: list[TensorSpec]
    bindings: list[GraphRuntimeBinding]
    compatible: bool
    kernel_rebinding: bool
    note: str


class GraphOptimizeOptions:
    enable_buffer_reuse: bool
    shape_polymorphic: bool
    def __init__(self) -> None: ...


class CapturedGraph:
    def size(self) -> int: ...
    def empty(self) -> bool: ...
    def replayable(self) -> bool: ...
    def rebindable(self) -> bool: ...
    def replay(self) -> None: ...
    def execute(self) -> None: ...
    def tensor_specs_list(self) -> list[TensorSpec]: ...
    def plan_buffers(self, options: GraphOptimizeOptions = ...) -> GraphBufferPlan: ...
    def compile_runtime_plan(self, runtime_specs: Sequence[TensorSpec], options: GraphOptimizeOptions = ...) -> GraphRuntimePlan: ...


class GraphExecutor:
    def execute(self) -> None: ...
    def replayable(self) -> bool: ...
    def rebindable(self) -> bool: ...
    def bind_tensor(self, captured_tensor_id: int, tensor: Tensor) -> None: ...
    def clear_bindings(self) -> None: ...
    def bound_tensor_count(self) -> int: ...
    def executions(self) -> int: ...
    def execution_mode(self) -> str: ...
    @property
    def runtime_plan(self) -> GraphRuntimePlan: ...


class GraphCaptureGuard:
    def __init__(self) -> None: ...
    def finish(self) -> CapturedGraph: ...


class Parameter:
    def __init__(self, tensor: Tensor, trainable: bool = True) -> None: ...
    data: Tensor
    trainable: bool
    def grad(self) -> Tensor: ...
    def zero_grad(self) -> None: ...


class Module:
    def forward(self, x: Tensor) -> Tensor: ...
    def zero_grad(self) -> None: ...


class Linear(Module):
    def __init__(self, backend: Backend, in_features: int, out_features: int, bias: bool = True) -> None: ...
    weight: Parameter
    bias: Parameter
    def parameters(self) -> list[Parameter]: ...
    def has_bias(self) -> bool: ...
    def enable_quantized_inference(self, qdtype: DType = DType.Q4_0) -> None: ...
    def set_quantized_weight(self, weight: Tensor) -> None: ...
    def disable_quantized_inference(self) -> None: ...
    def quantized_inference_enabled(self) -> bool: ...
    def quantized_weight_dtype(self) -> DType: ...
    def quantized_weight(self) -> Tensor: ...


class QuantizedLinear(Module):
    def __init__(self, weight: Tensor, bias_or_qdtype: object = ..., qdtype: DType = DType.Q4_0) -> None: ...
    @staticmethod
    def from_linear(linear: Linear, qdtype: DType = DType.Q4_0) -> QuantizedLinear: ...
    def parameters(self) -> list[Parameter]: ...
    def quantized_weight(self) -> Tensor: ...
    def bias(self) -> Tensor: ...
    def has_bias(self) -> bool: ...
    def weight_dtype(self) -> DType: ...
    def in_features(self) -> int: ...
    def out_features(self) -> int: ...


class GELU(Module): ...


class Sequential(Module):
    def __init__(self, modules: Sequence[Module]) -> None: ...
    def add(self, module: Module) -> None: ...
    def parameters(self) -> list[Parameter]: ...


class GPTModel(Module):
    def __init__(self, backend: Backend, vocab_size: int, block_size: int, n_embd: int, n_head: int, n_layer: int, mlp_hidden: int) -> None: ...
    def parameters(self) -> list[Parameter]: ...


class TransformerConfig:
    vocab_size: int
    block_size: int
    n_embd: int
    n_head: int
    n_kv_head: int
    n_layer: int
    mlp_hidden: int
    dropout: float
    use_rope: bool
    use_swiglu: bool
    use_qkv_bias: bool
    causal: bool
    learned_position_embeddings: bool
    rope_theta: float
    rotary_dim: int
    def __init__(self) -> None: ...


class KVCache:
    k: Tensor
    v: Tensor
    batch_size: int
    max_seq_len: int
    length: int
    n_kv_head: int
    head_dim: int
    def __init__(self, backend: Optional[Backend] = ..., batch_size: int = ..., max_seq_len: int = ..., n_kv_head: int = ..., head_dim: int = ...) -> None: ...
    def reset(self) -> None: ...


class ModernMLP(Module):
    use_swiglu: bool
    dropout_p: float
    def __init__(self, backend: Backend, n_embd: int, hidden: int, use_swiglu: bool = True, use_bias: bool = False, dropout: float = 0.0) -> None: ...
    def parameters(self) -> list[Parameter]: ...
    def enable_quantized_inference(self, qdtype: DType = DType.Q4_0) -> None: ...
    def disable_quantized_inference(self) -> None: ...
    def quantized_inference_enabled(self) -> bool: ...
    def quantized_weight_dtype(self) -> DType: ...


class ModernSelfAttention(Module):
    def __init__(self, backend: Backend, config: TransformerConfig) -> None: ...
    def forward(self, x: Tensor, batch_size: int = ..., seq_len: int = ..., causal: bool = True) -> Tensor: ...
    def forward_masked(self, x: Tensor, mask: Tensor, batch_size: int, seq_len: int, causal: bool = True) -> Tensor: ...
    def forward_with_cache(self, x: Tensor, cache: KVCache, batch_size: int, seq_len: int) -> Tensor: ...
    def forward_with_cache_masked(self, x: Tensor, mask: Tensor, cache: KVCache, batch_size: int, seq_len: int) -> Tensor: ...
    def parameters(self) -> list[Parameter]: ...
    def n_head(self) -> int: ...
    def n_kv_head(self) -> int: ...
    def head_dim(self) -> int: ...
    def enable_quantized_inference(self, qdtype: DType = DType.Q4_0) -> None: ...
    def disable_quantized_inference(self) -> None: ...
    def quantized_inference_enabled(self) -> bool: ...
    def quantized_weight_dtype(self) -> DType: ...


class ModernTransformerBlock(Module):
    def __init__(self, backend: Backend, config: TransformerConfig) -> None: ...
    def forward(self, x: Tensor, batch_size: int = ..., seq_len: int = ...) -> Tensor: ...
    def forward_masked(self, x: Tensor, mask: Tensor, batch_size: int, seq_len: int) -> Tensor: ...
    def forward_with_cache(self, x: Tensor, cache: KVCache, batch_size: int, seq_len: int) -> Tensor: ...
    def forward_with_cache_masked(self, x: Tensor, mask: Tensor, cache: KVCache, batch_size: int, seq_len: int) -> Tensor: ...
    def parameters(self) -> list[Parameter]: ...
    def enable_quantized_inference(self, qdtype: DType = DType.Q4_0) -> None: ...
    def disable_quantized_inference(self) -> None: ...
    def quantized_inference_enabled(self) -> bool: ...
    def quantized_weight_dtype(self) -> DType: ...


class QuantizationPolicy:
    default_dtype: DType
    lm_head_dtype: DType
    q8_layers: list[int]
    def __init__(self) -> None: ...


class ModernGPTModel(Module):
    config: TransformerConfig
    def __init__(self, backend: Backend, config: TransformerConfig) -> None: ...
    def forward_masked(self, token_ids: Tensor, mask: Tensor) -> Tensor: ...
    def forward_with_cache(self, token_ids: Tensor, caches: Sequence[KVCache]) -> Tensor: ...
    def forward_with_cache_masked(self, token_ids: Tensor, mask: Tensor, caches: Sequence[KVCache]) -> Tensor: ...
    def parameters(self) -> list[Parameter]: ...
    def create_kv_cache(self, backend: Backend, batch_size: int) -> list[KVCache]: ...
    def enable_quantized_inference(self, qdtype: DType = DType.Q4_0) -> None: ...
    def enable_quantized_inference_policy(self, policy: QuantizationPolicy) -> None: ...
    def set_quantized_lm_head(self, weight: Tensor) -> None: ...
    def disable_quantized_inference(self) -> None: ...
    def quantized_inference_enabled(self) -> bool: ...
    def quantized_weight_dtype(self) -> DType: ...
    def quantized_lm_head(self) -> Tensor: ...


class GemmaConfig:
    vocab_size: int
    max_position_embeddings: int
    hidden_size: int
    intermediate_size: int
    num_hidden_layers: int
    num_attention_heads: int
    num_key_value_heads: int
    head_dim: int
    rms_norm_eps: float
    rope_theta: float
    attention_dropout: float
    attention_bias: bool
    tie_word_embeddings: bool
    bos_token_id: int
    eos_token_id: int
    pad_token_id: int
    sliding_window: int
    def __init__(self) -> None: ...


class GemmaWeightName:
    hf_name: str
    internal_name: str
    kind: str
    layer: int


class GemmaWeightLoadReport:
    loaded_tensors: int
    applied: list[str]
    missing: list[str]
    unexpected: list[str]


class GemmaTokenizer:
    def __init__(self) -> None: ...
    @staticmethod
    def byte_fallback(vocab_size: int = 256, bos_token_id: int = 1, eos_token_id: int = 2) -> GemmaTokenizer: ...
    @staticmethod
    def load_vocab(path: str, bos_token_id: int = 1, eos_token_id: int = 2) -> GemmaTokenizer: ...
    def encode(self, text: str, add_bos: bool = False, add_eos: bool = False) -> list[int]: ...
    def decode(self, ids: Sequence[int], skip_special: bool = True) -> str: ...
    def vocab_size(self) -> int: ...
    def bos_token_id(self) -> int: ...
    def eos_token_id(self) -> int: ...
    def is_byte_fallback(self) -> bool: ...
    def tokenizer_model_type(self) -> str: ...


class GenerateOptions:
    max_new_tokens: int
    temperature: float
    top_k: int
    top_p: float
    bos_token_id: int
    eos_token_id: int
    pad_token_id: int
    add_bos: bool
    prefill_prompt: bool
    gpu_greedy_sampling: bool
    seed: int
    def __init__(self) -> None: ...


class HFArchitecture(Enum):
    Auto: int
    GenericDecoder: int
    Gemma: int
    Llama: int
    Mistral: int
    Qwen2: int


class HFTransformerConfig:
    architecture: HFArchitecture
    architecture_name: str
    transformer: TransformerConfig
    rms_norm_eps: float
    tie_word_embeddings: bool
    attention_bias: bool
    bos_token_id: int
    eos_token_id: int
    pad_token_id: int
    sliding_window: int
    def __init__(self) -> None: ...


HFWeightName = GemmaWeightName
HFWeightLoadReport = GemmaWeightLoadReport
HFTokenizer = GemmaTokenizer


class Adam:
    def __init__(self, params: Sequence[Parameter], lr: float = 1e-3, beta1: float = 0.9, beta2: float = 0.999, eps: float = 1e-8, weight_decay: float = 0.0) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...
    def set_lr(self, lr: float) -> None: ...
    def lr(self) -> float: ...
    def set_weight_decay(self, weight_decay: float) -> None: ...
    def weight_decay(self) -> float: ...


class LossScaleUpdate:
    found_inf: bool
    scale: float


class DynamicLossScaler:
    def __init__(self, initial_scale: float = 65536.0, growth_factor: float = 2.0, backoff_factor: float = 0.5, growth_interval: int = 2000) -> None: ...
    def scale_loss(self, loss: Tensor) -> Tensor: ...
    def unscale_(self, params: Sequence[Parameter]) -> None: ...
    def has_overflow(self, params: Sequence[Parameter]) -> bool: ...
    def update(self, found_inf: bool) -> LossScaleUpdate: ...
    def scale(self) -> float: ...
    def set_scale(self, scale: float) -> None: ...
    def growth_tracker(self) -> int: ...


class MixedPrecisionAdam:
    def __init__(self, params: Sequence[Parameter], lr: float = 1e-3, beta1: float = 0.9, beta2: float = 0.999, eps: float = 1e-8, weight_decay: float = 0.0) -> None: ...
    def step(self) -> None: ...
    def step_scaled(self, scaler: DynamicLossScaler) -> bool: ...
    def zero_grad(self) -> None: ...
    def set_lr(self, lr: float) -> None: ...
    def lr(self) -> float: ...
    def set_weight_decay(self, weight_decay: float) -> None: ...
    def weight_decay(self) -> float: ...
    def step_count(self) -> int: ...
    def refresh_master_from_params(self) -> None: ...


class SGD:
    def __init__(self, params: Sequence[Parameter], lr: float = 1e-2) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...
    def set_lr(self, lr: float) -> None: ...
    def lr(self) -> float: ...


def manual_seed(seed: int) -> None: ...
def is_grad_enabled() -> bool: ...
def set_grad_enabled(enabled: bool) -> None: ...

class no_grad:
    def __enter__(self) -> no_grad: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> bool: ...

def begin_graph_capture() -> None: ...
def end_graph_capture() -> CapturedGraph: ...
def compile_graph_executor(graph: CapturedGraph, options: GraphOptimizeOptions = ...) -> GraphExecutor: ...
def clear_memory_pool() -> None: ...
def memory_pool_cached_blocks() -> int: ...
def memory_pool_cached_bytes() -> int: ...
def backend_supports_fp16(backend: Backend) -> bool: ...
def randn(backend: Backend, shape: Sequence[int], std: float = 0.02) -> Tensor: ...
def uniform(backend: Backend, shape: Sequence[int], low: float = -1.0, high: float = 1.0) -> Tensor: ...
def zeros(backend: Backend, shape: Sequence[int], dtype: DType = DType.F32) -> Tensor: ...
def ones(backend: Backend, shape: Sequence[int], dtype: DType = DType.F32) -> Tensor: ...
def tensor_f32(backend: Backend, shape: Sequence[int], values: Sequence[float]) -> Tensor: ...
def tensor_i32(backend: Backend, shape: Sequence[int], values: Sequence[int]) -> Tensor: ...
def load_safetensors(backend: Backend, paths: Sequence[str], force_f32: bool = True) -> dict[str, Tensor]: ...
def add(a: Tensor, b: Tensor) -> Tensor: ...
def add_broadcast(a: Tensor, b: Tensor) -> Tensor: ...
def add_bias_gelu_rows(x: Tensor, bias: Tensor) -> Tensor: ...
def swiglu(packed: Tensor) -> Tensor: ...
def mul(a: Tensor, b: Tensor) -> Tensor: ...
def mul_broadcast(a: Tensor, b: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def matmul_f16_accum_f32(a: Tensor, b: Tensor) -> Tensor: ...
def cast_f32_to_f16(x: Tensor) -> Tensor: ...
def cast_f16_to_f32(x: Tensor) -> Tensor: ...
def mean_all(x: Tensor) -> Tensor: ...
def sum_all(x: Tensor) -> Tensor: ...
def rowwise_sum(x: Tensor) -> Tensor: ...
def rowwise_max(x: Tensor) -> Tensor: ...
def rowwise_argmax(x: Tensor) -> Tensor: ...
def rowwise_sample(x: Tensor, temperature: float = 0.0, top_k: int = 0, top_p: float = 1.0, seed: int = 1234) -> Tensor: ...
def slice_rows(x: Tensor, start: int, end: int) -> Tensor: ...
def dropout(x: Tensor, p: float = 0.5, training: bool = True) -> Tensor: ...
def masked_fill(x: Tensor, mask: Tensor, value: float) -> Tensor: ...
def qkv_split(packed: Tensor, q_dim: int, kv_dim: int) -> QKV: ...
def rope(x: Tensor, n_head: int, batch_size: int, seq_len: int, theta: float = 10000.0, rotary_dim: int = 0, token_offset: int = 0) -> Tensor: ...
def rope_positions(x: Tensor, positions: Tensor, n_head: int, batch_size: int, seq_len: int, theta: float = 10000.0, rotary_dim: int = 0) -> Tensor: ...
def multihead_attention(q: Tensor, k: Tensor, v: Tensor, n_head: int, causal: bool = False, batch_size: int = 1, seq_len: int = 0) -> Tensor: ...
def grouped_query_attention(q: Tensor, k: Tensor, v: Tensor, n_head: int, n_kv_head: int, causal: bool = True, batch_size: int = 1, query_len: int = 0, key_len: int = 0, query_offset: int = 0) -> Tensor: ...
def grouped_query_attention_masked(q: Tensor, k: Tensor, v: Tensor, mask: Tensor, n_head: int, n_kv_head: int, causal: bool = True, batch_size: int = 1, query_len: int = 0, key_len: int = 0, query_offset: int = 0, additive_mask: bool = False) -> Tensor: ...
def kv_cache_append(new_k: Tensor, new_v: Tensor, cache_k: Tensor, cache_v: Tensor, batch_size: int, new_tokens: int, max_tokens: int, start_pos: int) -> None: ...
def kv_cache_append_positions(new_k: Tensor, new_v: Tensor, positions: Tensor, cache_k: Tensor, cache_v: Tensor, batch_size: int, new_tokens: int, max_tokens: int) -> None: ...
def mse_loss(pred: Tensor, target: Tensor) -> Tensor: ...
def save_tensor(tensor: Tensor, path: str) -> None: ...
def load_tensor(backend: Backend, path: str) -> Tensor: ...
def save_quantized_transformer_checkpoint(model: ModernGPTModel, dir: str, qdtype: DType = DType.Q4_0) -> None: ...
def save_quantized_transformer_checkpoint_policy(model: ModernGPTModel, dir: str, policy: QuantizationPolicy) -> None: ...
def load_quantized_transformer_checkpoint(model: ModernGPTModel, backend: Backend, dir: str) -> None: ...
def load_gemma_config_json(path: str) -> GemmaConfig: ...
def to_transformer_config(config: GemmaConfig) -> TransformerConfig: ...
def make_gemma_model(backend: Backend, config: GemmaConfig) -> ModernGPTModel: ...
def map_gemma_hf_weight_name(hf_name: str) -> GemmaWeightName: ...
def expected_gemma_hf_weight_names(config: GemmaConfig, include_lm_head: bool = True) -> list[str]: ...
def load_gemma_hf_weights(backend: Backend, model: ModernGPTModel, safetensors_paths: Sequence[str], config: GemmaConfig, strict: bool = False, trainable: bool = False) -> GemmaWeightLoadReport: ...
def generate(backend: Backend, model: ModernGPTModel, prompt_tokens: Sequence[int], options: GenerateOptions = ...) -> list[int]: ...
def generate_text(backend: Backend, model: ModernGPTModel, tokenizer: GemmaTokenizer, prompt: str, options: GenerateOptions = ...) -> str: ...
def generate_batch(backend: Backend, model: ModernGPTModel, prompt_tokens: Sequence[Sequence[int]], options: GenerateOptions = ...) -> list[list[int]]: ...
def generate_batch_text(backend: Backend, model: ModernGPTModel, tokenizer: GemmaTokenizer, prompts: Sequence[str], options: GenerateOptions = ...) -> list[str]: ...
def hf_architecture_name(architecture: HFArchitecture) -> str: ...
def parse_hf_architecture(value: str) -> HFArchitecture: ...
def load_hf_transformer_config_json(path: str, architecture: HFArchitecture = HFArchitecture.Auto) -> HFTransformerConfig: ...
def to_gemma_compatible_config(config: HFTransformerConfig) -> GemmaConfig: ...
def make_hf_transformer_model(backend: Backend, config: HFTransformerConfig) -> ModernGPTModel: ...
def map_hf_transformer_weight_name(architecture: HFArchitecture, hf_name: str) -> HFWeightName: ...
def expected_hf_transformer_weight_names(config: HFTransformerConfig, include_lm_head: bool = True) -> list[str]: ...
def load_hf_transformer_weights(backend: Backend, model: ModernGPTModel, safetensors_paths: Sequence[str], config: HFTransformerConfig, strict: bool = False, trainable: bool = False) -> HFWeightLoadReport: ...
def enable_hf_transformer_quantized_inference(model: ModernGPTModel, qdtype: DType = DType.Q4_0) -> None: ...
def disable_hf_transformer_quantized_inference(model: ModernGPTModel) -> None: ...
def load_hf_tokenizer(model_dir_or_vocab_path: str, config: HFTransformerConfig) -> HFTokenizer: ...
def generate_hf_text(backend: Backend, model: ModernGPTModel, tokenizer: HFTokenizer, prompt: str, options: GenerateOptions = ...) -> str: ...
def generate_hf_batch_text(backend: Backend, model: ModernGPTModel, tokenizer: HFTokenizer, prompts: Sequence[str], options: GenerateOptions = ...) -> list[str]: ...
