from __future__ import annotations

from enum import Enum
from typing import Callable, Iterable, Optional, Sequence


class DType(Enum):
    F32: int
    F16: int
    I32: int
    U8: int
    Q8_0: int
    Q4_0: int


class DeviceInfo:
    platform_name: str
    platform_vendor: str
    device_name: str
    device_vendor: str
    driver_version: str
    device_version: str
    extensions: str
    global_mem_size: int
    local_mem_size: int
    compute_units: int
    max_work_group_size: int


class ProfileRecord:
    name: str
    ms: float


class ProfileSummary:
    name: str
    count: int
    total_ms: float
    avg_ms: float
    max_ms: float


class Backend:
    @staticmethod
    def opencl(kernel_dir: str = "") -> Backend: ...
    @staticmethod
    def create() -> Backend: ...
    def finish(self) -> None: ...
    def device_info(self) -> DeviceInfo: ...
    def supports_integer_dot(self) -> bool: ...
    def int_dot_mode(self) -> str: ...
    def profile_set_enabled(self, enabled: bool) -> None: ...
    def profile_enabled(self) -> bool: ...
    def profile_clear(self) -> None: ...
    def profile_records(self) -> list[ProfileRecord]: ...
    def profile_summary(self) -> list[ProfileSummary]: ...


class Tensor:
    @property
    def shape(self) -> list[int]: ...
    @property
    def dtype(self) -> DType: ...
    @property
    def requires_grad(self) -> bool: ...
    def id(self) -> int: ...
    def cpu(self) -> list[float]: ...
    def cpu_i32(self) -> list[int]: ...
    def item(self) -> float: ...
    def backward(self) -> None: ...
    def set_requires_grad(self, value: bool = True) -> None: ...
    def view(self, shape: Sequence[int]) -> Tensor: ...


class QKV:
    q: Tensor
    k: Tensor
    v: Tensor


class TensorSpec:
    id: int
    dtype: DType
    nbytes: int
    dynamic_shape: bool
    @property
    def shape(self) -> list[int]: ...


class GraphBufferAllocation:
    allocation_id: int
    tensor_ids: list[int]
    bytes: int
    first_node: int
    last_node: int


class GraphBufferPlan:
    allocations: list[GraphBufferAllocation]
    peak_bytes: int
    total_output_bytes: int
    reused_bytes: int
    shape_polymorphic: bool


class GraphRuntimeBinding:
    tensor_id: int
    allocation_id: int
    offset: int
    nbytes: int
    dtype: DType
    @property
    def shape(self) -> list[int]: ...


class GraphRuntimePlan:
    buffer_plan: GraphBufferPlan
    runtime_specs: list[TensorSpec]
    bindings: list[GraphRuntimeBinding]
    compatible: bool
    kernel_rebinding: bool
    note: str


class GraphOptimizeOptions:
    enable_buffer_reuse: bool
    shape_polymorphic: bool
    def __init__(self) -> None: ...


class CapturedGraph:
    def size(self) -> int: ...
    def empty(self) -> bool: ...
    def replayable(self) -> bool: ...
    def replay(self) -> None: ...
    def execute(self) -> None: ...
    def tensor_specs_list(self) -> list[TensorSpec]: ...
    def plan_buffers(self, options: GraphOptimizeOptions = ...) -> GraphBufferPlan: ...
    def compile_runtime_plan(self, runtime_specs: Sequence[TensorSpec], options: GraphOptimizeOptions = ...) -> GraphRuntimePlan: ...


class GraphExecutor:
    def execute(self) -> None: ...
    def replayable(self) -> bool: ...
    def executions(self) -> int: ...
    @property
    def runtime_plan(self) -> GraphRuntimePlan: ...


class GraphCaptureGuard:
    def __init__(self) -> None: ...
    def finish(self) -> CapturedGraph: ...


class Parameter:
    @property
    def data(self) -> Tensor: ...
    def zero_grad(self) -> None: ...


class Module:
    def forward(self, x: Tensor) -> Tensor: ...
    def zero_grad(self) -> None: ...


class Linear(Module):
    def __init__(self, backend: Backend, in_features: int, out_features: int, bias: bool = True) -> None: ...
    def parameters(self) -> list[Parameter]: ...


class GELU(Module): ...


class Sequential(Module):
    def __init__(self, modules: Sequence[Module]) -> None: ...
    def add(self, module: Module) -> None: ...
    def parameters(self) -> list[Parameter]: ...


class GPTModel(Module):
    def __init__(self, backend: Backend, vocab_size: int, block_size: int, n_embd: int, n_head: int, n_layer: int, mlp_hidden: int) -> None: ...
    def parameters(self) -> list[Parameter]: ...


class TransformerConfig:
    vocab_size: int
    block_size: int
    n_embd: int
    n_head: int
    n_kv_head: int
    n_layer: int
    mlp_hidden: int
    dropout: float
    use_rope: bool
    use_swiglu: bool
    use_qkv_bias: bool
    causal: bool
    learned_position_embeddings: bool
    rope_theta: float
    rotary_dim: int
    def __init__(self) -> None: ...


class KVCache:
    k: Tensor
    v: Tensor
    batch_size: int
    max_seq_len: int
    length: int
    n_kv_head: int
    head_dim: int
    def __init__(self, backend: Optional[Backend] = ..., batch_size: int = ..., max_seq_len: int = ..., n_kv_head: int = ..., head_dim: int = ...) -> None: ...
    def reset(self) -> None: ...


class ModernMLP(Module):
    use_swiglu: bool
    dropout_p: float
    def __init__(self, backend: Backend, n_embd: int, hidden: int, use_swiglu: bool = True, use_bias: bool = False, dropout: float = 0.0) -> None: ...
    def parameters(self) -> list[Parameter]: ...


class ModernSelfAttention(Module):
    def __init__(self, backend: Backend, config: TransformerConfig) -> None: ...
    def forward(self, x: Tensor, batch_size: int = ..., seq_len: int = ..., causal: bool = True) -> Tensor: ...
    def forward_masked(self, x: Tensor, mask: Tensor, batch_size: int, seq_len: int, causal: bool = True) -> Tensor: ...
    def forward_with_cache(self, x: Tensor, cache: KVCache, batch_size: int, seq_len: int) -> Tensor: ...
    def forward_with_cache_masked(self, x: Tensor, mask: Tensor, cache: KVCache, batch_size: int, seq_len: int) -> Tensor: ...
    def parameters(self) -> list[Parameter]: ...
    def n_head(self) -> int: ...
    def n_kv_head(self) -> int: ...
    def head_dim(self) -> int: ...


class ModernTransformerBlock(Module):
    def __init__(self, backend: Backend, config: TransformerConfig) -> None: ...
    def forward(self, x: Tensor, batch_size: int = ..., seq_len: int = ...) -> Tensor: ...
    def forward_masked(self, x: Tensor, mask: Tensor, batch_size: int, seq_len: int) -> Tensor: ...
    def forward_with_cache(self, x: Tensor, cache: KVCache, batch_size: int, seq_len: int) -> Tensor: ...
    def forward_with_cache_masked(self, x: Tensor, mask: Tensor, cache: KVCache, batch_size: int, seq_len: int) -> Tensor: ...
    def parameters(self) -> list[Parameter]: ...


class ModernGPTModel(Module):
    config: TransformerConfig
    def __init__(self, backend: Backend, config: TransformerConfig) -> None: ...
    def forward_masked(self, token_ids: Tensor, mask: Tensor) -> Tensor: ...
    def forward_with_cache(self, token_ids: Tensor, caches: Sequence[KVCache]) -> Tensor: ...
    def forward_with_cache_masked(self, token_ids: Tensor, mask: Tensor, caches: Sequence[KVCache]) -> Tensor: ...
    def parameters(self) -> list[Parameter]: ...
    def create_kv_cache(self, backend: Backend, batch_size: int) -> list[KVCache]: ...


class Adam:
    def __init__(self, params: Sequence[Parameter], lr: float = 1e-3, beta1: float = 0.9, beta2: float = 0.999, eps: float = 1e-8) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...
    def set_lr(self, lr: float) -> None: ...
    def lr(self) -> float: ...


class SGD:
    def __init__(self, params: Sequence[Parameter], lr: float = 1e-2) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...
    def set_lr(self, lr: float) -> None: ...
    def lr(self) -> float: ...


def manual_seed(seed: int) -> None: ...
def begin_graph_capture() -> None: ...
def end_graph_capture() -> CapturedGraph: ...
def compile_graph_executor(graph: CapturedGraph, options: GraphOptimizeOptions = ...) -> GraphExecutor: ...
def clear_memory_pool() -> None: ...
def memory_pool_cached_blocks() -> int: ...
def memory_pool_cached_bytes() -> int: ...
def backend_supports_fp16(backend: Backend) -> bool: ...
def randn(backend: Backend, shape: Sequence[int], std: float = 0.02) -> Tensor: ...
def uniform(backend: Backend, shape: Sequence[int], low: float = -1.0, high: float = 1.0) -> Tensor: ...
def zeros(backend: Backend, shape: Sequence[int], dtype: DType = DType.F32) -> Tensor: ...
def ones(backend: Backend, shape: Sequence[int], dtype: DType = DType.F32) -> Tensor: ...
def tensor_f32(backend: Backend, shape: Sequence[int], values: Sequence[float]) -> Tensor: ...
def tensor_i32(backend: Backend, shape: Sequence[int], values: Sequence[int]) -> Tensor: ...
def add(a: Tensor, b: Tensor) -> Tensor: ...
def add_broadcast(a: Tensor, b: Tensor) -> Tensor: ...
def add_bias_gelu_rows(x: Tensor, bias: Tensor) -> Tensor: ...
def swiglu(packed: Tensor) -> Tensor: ...
def mul(a: Tensor, b: Tensor) -> Tensor: ...
def mul_broadcast(a: Tensor, b: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def matmul_f16_accum_f32(a: Tensor, b: Tensor) -> Tensor: ...
def cast_f32_to_f16(x: Tensor) -> Tensor: ...
def cast_f16_to_f32(x: Tensor) -> Tensor: ...
def mean_all(x: Tensor) -> Tensor: ...
def sum_all(x: Tensor) -> Tensor: ...
def slice_rows(x: Tensor, start: int, end: int) -> Tensor: ...
def dropout(x: Tensor, p: float = 0.5, training: bool = True) -> Tensor: ...
def masked_fill(x: Tensor, mask: Tensor, value: float) -> Tensor: ...
def qkv_split(packed: Tensor, q_dim: int, kv_dim: int) -> QKV: ...
def rope(x: Tensor, n_head: int, batch_size: int, seq_len: int, theta: float = 10000.0, rotary_dim: int = 0, token_offset: int = 0) -> Tensor: ...
def multihead_attention(q: Tensor, k: Tensor, v: Tensor, n_head: int, causal: bool = False, batch_size: int = 1, seq_len: int = 0) -> Tensor: ...
def grouped_query_attention(q: Tensor, k: Tensor, v: Tensor, n_head: int, n_kv_head: int, causal: bool = True, batch_size: int = 1, query_len: int = 0, key_len: int = 0, query_offset: int = 0) -> Tensor: ...
def grouped_query_attention_masked(q: Tensor, k: Tensor, v: Tensor, mask: Tensor, n_head: int, n_kv_head: int, causal: bool = True, batch_size: int = 1, query_len: int = 0, key_len: int = 0, query_offset: int = 0, additive_mask: bool = False) -> Tensor: ...
def kv_cache_append(new_k: Tensor, new_v: Tensor, cache_k: Tensor, cache_v: Tensor, batch_size: int, new_tokens: int, max_tokens: int, start_pos: int) -> None: ...
def mse_loss(pred: Tensor, target: Tensor) -> Tensor: ...
def save_tensor(tensor: Tensor, path: str) -> None: ...
def load_tensor(backend: Backend, path: str) -> Tensor: ...
