#pragma once

#include <motifcl/core/device.hpp>
#include <motifcl/core/dtype.hpp>
#include <motifcl/core/error.hpp>
#include <motifcl/core/shape.hpp>
#include <motifcl/core/status.hpp>
#include <motifcl/core/types.hpp>
#include <motifcl/runtime/backend.hpp>
#include <motifcl/runtime/buffer.hpp>
#include <motifcl/runtime/command_buffer.hpp>
#include <motifcl/runtime/kernel.hpp>
#include <motifcl/runtime/opencl_context.hpp>
#include <motifcl/runtime/program.hpp>
#include <motifcl/tensor/tensor.hpp>
#include <motifcl/ops/basic_ops.hpp>
#include <motifcl/ops/fp16.hpp>
#include <motifcl/ops/matmul.hpp>
#include <motifcl/ops/reduce.hpp>
#include <motifcl/ops/indexing.hpp>
#include <motifcl/ops/activation.hpp>
#include <motifcl/ops/fused_transformer.hpp>
#include <motifcl/ops/norm.hpp>
#include <motifcl/ops/attention.hpp>
#include <motifcl/ops/loss.hpp>
#include <motifcl/ops/optim.hpp>
#include <motifcl/autograd/graph.hpp>
#include <motifcl/ops/quant.hpp>
#include <motifcl/autograd/backward.hpp>
#include <motifcl/nn/module.hpp>
#include <motifcl/nn/linear.hpp>
#include <motifcl/nn/embedding.hpp>
#include <motifcl/nn/rmsnorm.hpp>
#include <motifcl/nn/attention.hpp>
#include <motifcl/nn/mlp.hpp>
#include <motifcl/nn/transformer.hpp>
#include <motifcl/nn/gemma.hpp>
#include <motifcl/nn/hf_compat.hpp>
#include <motifcl/motif/motif_linear.hpp>
#include <motifcl/motif/motif_lora.hpp>
#include <motifcl/motif/router.hpp>
#include <motifcl/motif/motif_block.hpp>
#include <motifcl/motif/sarc_residual.hpp>
#include <motifcl/train/adam.hpp>
#include <motifcl/train/mixed_precision.hpp>
#include <motifcl/train/static_train_step.hpp>
#include <motifcl/train/sgd.hpp>
#include <motifcl/train/dataloader.hpp>
#include <motifcl/train/scheduler.hpp>
#include <motifcl/train/training_utils.hpp>
#include <motifcl/train/trainer.hpp>
#include <motifcl/serialization.hpp>

namespace mcl = motifcl;
