#!/usr/bin/env python3
"""Compile kernels/vulkan/*.comp into an embedded SPIR-V C++ header.

The generated file (src/runtime/vulkan_spirv_kernels.inc) is committed to the
repository so the normal build has no shader-compiler dependency.  Re-run this
script after editing any .comp source:

    python tools/gen_vulkan_spirv.py

glslc is located via (in order): MOTIFCL_GLSLC env var, PATH, then the newest
Android NDK shader-tools directory if an Android SDK is installed.
"""

import os
import glob
import shutil
import struct
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADER_DIR = os.path.join(ROOT, "kernels", "vulkan")
OUTPUT = os.path.join(ROOT, "src", "runtime", "vulkan_spirv_kernels.inc")


def find_glslc():
    env = os.environ.get("MOTIFCL_GLSLC")
    if env and os.path.isfile(env):
        return env
    on_path = shutil.which("glslc")
    if on_path:
        return on_path
    sdk = os.environ.get("ANDROID_SDK_ROOT") or os.path.expandvars(
        r"%LOCALAPPDATA%\Android\Sdk"
    )
    candidates = sorted(
        glob.glob(os.path.join(sdk, "ndk", "*", "shader-tools", "*", "glslc*"))
    )
    for candidate in reversed(candidates):
        if os.path.isfile(candidate) and not candidate.endswith(".pdb"):
            return candidate
    raise SystemExit(
        "glslc not found: set MOTIFCL_GLSLC, add glslc to PATH, or install an Android NDK"
    )


def compile_shader(glslc, path):
    spv = path + ".spv.tmp"
    cmd = [
        glslc,
        "-fshader-stage=compute",
        # vulkan1.1 unlocks subgroup ops (subgroupAdd / subgroupBroadcast) used
        # by the reduction kernels (softmax_rows, rmsnorm, GQA backward, etc.)
        # to replace the manual shared-memory tree reduction (5 barriers +
        # 5 LDS round-trips per reduction). GCN4 (RX 580) exposes subgroupSize=64.
        "--target-env=vulkan1.1",
        "-O",
        path,
        "-o",
        spv,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"glslc failed for {path}:\n{result.stdout}{result.stderr}")
    with open(spv, "rb") as handle:
        blob = handle.read()
    os.remove(spv)
    if len(blob) % 4 != 0:
        raise SystemExit(f"SPIR-V for {path} is not word aligned")
    return struct.unpack(f"<{len(blob)//4}I", blob)


def main():
    glslc = find_glslc()
    sources = sorted(glob.glob(os.path.join(SHADER_DIR, "*.comp")))
    if not sources:
        raise SystemExit(f"no .comp sources under {SHADER_DIR}")
    lines = [
        "// Generated by tools/gen_vulkan_spirv.py — do not edit by hand.",
        "// Sources: kernels/vulkan/*.comp (GLSL compute, compiled with glslc",
        "// --target-env=vulkan1.0 -O).  Committed so builds need no shader",
        "// compiler; re-run the script after editing any kernel source.",
        "",
        "namespace vkspirv {",
        "",
    ]
    for path in sources:
        name = os.path.splitext(os.path.basename(path))[0]
        words = compile_shader(glslc, path)
        lines.append(f"// {os.path.relpath(path, ROOT).replace(os.sep, '/')}")
        lines.append(
            f"inline constexpr std::uint32_t k_{name}[] = {{"
        )
        for i in range(0, len(words), 8):
            chunk = ", ".join(f"0x{w:08x}u" for w in words[i : i + 8])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append(
            f"inline constexpr std::size_t k_{name}_words = "
            f"sizeof(k_{name}) / sizeof(k_{name}[0]);"
        )
        lines.append("")
        print(f"  {name}: {len(words)} words")
    lines.append("} // namespace vkspirv")
    lines.append("")
    with open(OUTPUT, "w", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUTPUT, ROOT)} ({len(sources)} kernels)")


if __name__ == "__main__":
    sys.exit(main())
